version: '3'
services:

  server:
    image: postgrest/postgrest:v5.2.0
    # restart: always
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      PGRST_DB_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db

  db:
    build:
      context: docker/postgres
#    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  adminer:
    image: adminer
    # restart: always
    ports:
      - 8081:8080

  swagger:
    image: swaggerapi/swagger-ui
    # restart: always
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000

  analyser:
    image: joriskok/korean_sentence_analyser:1.0.1
    container_name: analyser
    ports:
      - 5000:5000
        # restart: always

