version: '3'
services:

  server:
    image: postgrest/postgrest
    restart: always
    ports:
      - "3000:3000"
    links:
      - db:db
    environment:
      PGRST_DB_URI: postgres://korean_api:korean_api@db:5432/korean_api
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: web_anon #In production this role should not be the same as the one used for the connection
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: korean_api
      POSTGRES_USER: korean_api # TODO change for production
      POSTGRES_PASSWORD: korean_api # TODO change for production

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  swagger:
    image: swaggerapi/swagger-ui
    restart: always
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000

